import { z } from "zod";

/**
 * Study types supported by OpenField
 */
export const StudyTypeSchema = z.enum([
  "nature",
  "environment",
  "sound",
  "neighborhood",
  "photography",
]);
export type StudyType = z.infer<typeof StudyTypeSchema>;

/**
 * Valid study durations in minutes
 */
export const StudyMinutesSchema = z.union([
  z.literal(15),
  z.literal(30),
  z.literal(45),
  z.literal(60),
]);
export type StudyMinutes = z.infer<typeof StudyMinutesSchema>;

/**
 * Input submitted from Screen 1 (Create Study)
 */
export const StudyInputSchema = z.object({
  question: z.string().trim().min(3, "Question must be at least 3 characters"),
  place: z.string().trim().min(1, "Place is required"),
  minutes: StudyMinutesSchema,
  type: StudyTypeSchema,
});
export type StudyInput = z.infer<typeof StudyInputSchema>;

/**
 * Evidence modalities collected during a study
 */
export const EvidenceTypeSchema = z.enum([
  "photo",
  "note",
  "count",
  "measurement",
]);
export type EvidenceType = z.infer<typeof EvidenceTypeSchema>;

/**
 * A single protocol investigation step
 */
export const ProtocolStepSchema = z.object({
  id: z.string().min(1),
  instruction: z.string().min(1),
  evidence: EvidenceTypeSchema,
  required: z.boolean(),
});
export type ProtocolStep = z.infer<typeof ProtocolStepSchema>;

/**
 * Full Field Protocol generated by Gemma (Screen 2)
 * Must strictly contain 4 to 6 concrete steps per SPEC and ARCHITECTURE.
 */
export const FieldProtocolSchema = z.object({
  id: z.string().min(1),
  title: z.string().min(1),
  researchQuestion: z.string().min(1),
  minutes: StudyMinutesSchema,
  type: StudyTypeSchema,
  steps: z
    .array(ProtocolStepSchema)
    .min(4, "Protocol must have at least 4 steps")
    .max(6, "Protocol must have at most 6 steps"),
  evidenceNeeded: z.array(z.string().min(1)),
  safetyNote: z.string().min(1),
  audioScript: z.string().min(1),
});
export type FieldProtocol = z.infer<typeof FieldProtocolSchema>;

/**
 * Observation recorded on Screen 4 (Return)
 */
export const ObservationSchema = z.object({
  stepId: z.string().min(1),
  note: z.string().optional(),
  photoIds: z.array(z.string()).optional(),
  measured: z.boolean().optional(),
});
export type Observation = z.infer<typeof ObservationSchema>;

/**
 * Field Report produced on Screen 5 (Report)
 */
export const ReportFindingSchema = z.object({
  claim: z.string().min(1),
  evidenceRefs: z
    .array(z.string().min(1))
    .min(1, "Every finding must cite at least one evidence reference"),
  confidence: z.enum(["low", "medium", "high"]),
});

export const FieldReportSchema = z.object({
  findings: z.array(ReportFindingSchema),
  observed: z.array(z.string()),
  inferred: z.array(z.string()),
  uncertain: z.array(z.string()),
  evidenceSummary: z.object({
    photos: z.number().int().nonnegative(),
    notes: z.number().int().nonnegative(),
    measurements: z.number().int().nonnegative(),
  }),
  nextQuestion: z.string().min(1),
});
export type FieldReport = z.infer<typeof FieldReportSchema>;

/**
 * Standard typed errors for OpenField AI interactions
 */
export type ErrorCode =
  | "OLLAMA_UNREACHABLE"
  | "MODEL_NOT_FOUND"
  | "INVALID_MODEL_OUTPUT"
  | "TIMEOUT"
  | "VALIDATION_ERROR";

export interface AppError {
  code: ErrorCode;
  message: string;
  details?: string;
}
