/**
 * Pure display-time sanitization helper.
 * Enforces the strict zero em-dash and en-dash rule across all visible UI text,
 * including raw text generated by local Gemma models.
 * Does NOT alter underlying saved data or model payloads.
 */
export function sanitizeDisplayText(text: string | null | undefined): string {
  if (!text) return "";
  // Replace em-dash (—), en-dash (–), and horizontal bar (―) with a clean spaced hyphen or regular hyphen
  return text
    .replace(/\s*[—–―]\s*/g, " - ")
    .replace(/[—–―]/g, "-");
}

/**
 * Format counts with correct singular/plural forms to avoid "1 photos" bugs.
 */
export function formatPlural(count: number, singular: string, plural?: string): string {
  const pluralForm = plural || `${singular}s`;
  return `${count} ${count === 1 ? singular : pluralForm}`;
}
